# Configure Cloudflare Pages

name = "hosting-cloudflare-pages"
pages_build_output_dir = "public"

[vars]
DART_SASS_VERSION = "1.91.0"
GO_VERSION = "1.25.0"
HUGO_VERSION = "0.149.0"
NODE_VERSION = "22.18.0"
TZ = "Europe/Oslo"
