# Configure Cloudflare Pages

name = "hosting-cloudflare-pages"
pages_build_output_dir = "public"

[vars]
DART_SASS_VERSION = "1.93.3"
GO_VERSION = "1.25.4"
HUGO_VERSION = "0.152.2"
NODE_VERSION = "24.11.0"
TZ = "Europe/Oslo"
