# Configure Cloudflare Pages

name = "hosting-cloudflare-pages"
pages_build_output_dir = "public"

[vars]
DART_SASS_VERSION = "1.97.3"
GO_VERSION = "1.26.0"
HUGO_VERSION = "0.155.3"
NODE_VERSION = "24.13.1"
TZ = "Europe/Oslo"
